### ISSUE TITLE
BUG - Constraints are not present on join tables, allowing duplicated associations

### ISSUE THREAD

**Issue by andricDu** [overture-stack/ego#480]
## Description
Our join tables do not have proper constraints to ensure uniqueness of rows, allowing for double associations in the many-to-many relationships (duplicated join entries). 

You can see here usergroup and groupapplication join tables have no constraints on uniqueness: 
```sql
ego=# \d+ usergroup
                                Table "public.usergroup"
  Column  | Type | Collation | Nullable | Default | Storage | Stats target | Description 
----------+------+-----------+----------+---------+---------+--------------+-------------
 user_id  | uuid |           | not null |         | plain   |              | 
 group_id | uuid |           | not null |         | plain   |              | 
Indexes:
    "idx_usergroup_both" btree (user_id, group_id)
    "idx_usergroup_group" btree (group_id)
    "idx_usergroup_user" btree (user_id)
Foreign-key constraints:
    "usergroup_group_fkey" FOREIGN KEY (group_id) REFERENCES egogroup(id)
    "usergroup_user_fkey" FOREIGN KEY (user_id) REFERENCES egouser(id)

ego=# \d+ groupapplication
                                Table "public.groupapplication"
     Column     | Type | Collation | Nullable | Default | Storage | Stats target | Description 
----------------+------+-----------+----------+---------+---------+--------------+-------------
 group_id       | uuid |           | not null |         | plain   |              | 
 application_id | uuid |           | not null |         | plain   |              | 
Foreign-key constraints:
    "groupapplication_application_fkey" FOREIGN KEY (application_id) REFERENCES egoapplication(id)
    "groupapplication_group_fkey" FOREIGN KEY (group_id) REFERENCES egogroup(id)
```

While we have this:
```sql
CREATE TABLE USERGROUP (
  userId                UUID,
  grpId                 BIGSERIAL,
  PRIMARY KEY (grpId,userId),
  FOREIGN KEY (grpId)   REFERENCES EGOGROUP(id),
  FOREIGN KEY (userId)  REFERENCES EGOUSER(id)
);
```

We did not properly update the constraint when we renamed fields (notice the primary key constraint is missing):
```sql
ALTER TABLE USERGROUP RENAME USERID TO USER_ID;
ALTER TABLE USERGROUP RENAME GRPID TO GROUP_ID;
ALTER TABLE USERGROUP RENAME CONSTRAINT USERGROUP_GRPID_FKEY TO USERGROUP_GROUP_FKEY;
ALTER TABLE USERGROUP RENAME CONSTRAINT USERGROUP_USERID_FKEY TO USERGROUP_USER_FKEY;
```

## Expected Behaviour
* No double/triple/+ associations between entities 
* Can modify associations without internal server errors

## Actual Behaviour
Hibernate batches fail because it knows it shouldn't have multiple identical associations:
```log
INFO   | jvm 1    | 2020/06/25 10:18:26 | 2020-06-25 10:18:26,414 [http-nio-8088-exec-3] INFO  b.o.e.s.SecureAuthorizationManager - Authorization succeeded                                                                                                                                                                  
INFO   | jvm 1    | 2020/06/25 10:18:26 | 2020-06-25 10:18:26,457 [http-nio-8088-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException
: Batch update returned unexpected row count from update [0]; actual row count: 2; expected: 1; nested exception is org.hibernate.jdbc.BatchedTooManyRowsAffectedException: Batch update returned unexpected row count from update [0]; actual row count: 2; expected: 1] with root cause                                    
INFO   | jvm 1    | 2020/06/25 10:18:26 | org.hibernate.jdbc.BatchedTooManyRowsAffectedException: Batch update returned unexpected row count from update [0]; actual row count: 2; expected: 1                                                                                                                               
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:77)                                                                                                                                                                                       
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)                                                                                                                                                                                      
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)                                                                                                                                                                            
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3480)                                                                                                                                                                          
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3737)                                                                                                                                                                          
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:99)                                                                                                                                                                                      
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)                                                                                                                                                                                                 
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)                                                                                                                                                                                                 
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356)                                                                                                                                                      
INFO   | jvm 1    | 2020/06/25 10:18:26 |       at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:50)         
```

## Possible Fix
* Add unique constraints to all join tables.

**Comment by rtisma** [comment]
@dusan @lepsalex  if i recall, during roblex refactor, the constraint did not work well with hibernate. Since we are using 2 way one-to-many to do many-to-many, hibernate does not associate entities in 1 transaction, but rather in 2 transactions, which breaks the primary constraint. The impact of adding the suggested primary key may require some refactor in how we handle many to many transactions across all entities.

**Comment by andricDu** [comment]
@rtisma the lack of constraint does not work well with hibernate as hibernate computes expected update counts but it is mismatched due to duplicate rows. See the posted stack trace.

**Comment by rosibaj** [comment]
Will be upgraded in Platform next sprint: https://github.com/icgc-argo/roadmap/issues/509
