### ISSUE TITLE
BUG - Cannot login using the Quick Start instructions

### ISSUE THREAD

**Issue by tschaffter** [overture-stack/ego#648]
## Description
- I started the stack using the instructions from the Quick Start section (README).
  ```console
  API_HOST_PORT=8080 docker-compose up
  ```
- I can access the home page (http://localhost:8080/)
- Upon clicking on any of the buttons, I'm redirected to an unknown pages (`Unable to connect` in Firefox):
  ```
  http://localhost:8081/oauth/login/keycloak?client_id=ego-ui
  http://localhost:8081/oauth/login/google?client_id=ego-ui
  ...
  ```

## Expected Behaviour
I expect to be redirected to a page where I can login.

## Actual Behaviour
I'm redirected to an unknown page (`Unable to connect` in Firefox).

## Possible Fix
Maybe the port configuration is incorrect (8080 vs 8081)

## Steps to Reproduce
See section `Description`

## Your Environment

* Version used: commit `a59edd7775670a99188fe7a012d6a713f27e3f15`
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 100.0.2 (64-bit), Docker version 20.10.14, build a224086
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by tschaffter** [comment]
Thanks for the quick response, @blabadi. I pulled the latest commit from the `develop` branch. After starting the stack, the follow exception is generated when I navigate to `http://localhost:8080/`. The page looks good though.

```console
ego-ui_1    | Find out more about deployment here:
ego-ui_1    | 
ego-ui_1    |   https://cra.link/deployment
ego-ui_1    | 
ego-ui_1    | UPDATE AVAILABLE The latest version of `serve` is 13.0.2
ego-ui_1    | INFO: Accepting connections at http://localhost:8080
^Tlocaapi_1       | 2022-05-27 01:52:41,904 [http-nio-8081-exec-1] INFO  o.a.c.c.C.[.[.[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
api_1       | 2022-05-27 01:52:41,904 [http-nio-8081-exec-1] INFO  o.s.w.s.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
api_1       | 2022-05-27 01:52:41,905 [http-nio-8081-exec-1] INFO  o.s.w.s.DispatcherServlet - Completed initialization in 1 ms
api_1       | 2022-05-27 01:52:41,982 [http-nio-8081-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
api_1       | bio.overture.ego.model.exceptions.NotFoundException: The 'Application' entity with clientId 'ego-ui' was not found
api_1       |   at bio.overture.ego.model.exceptions.NotFoundException.checkNotFound(NotFoundException.java:35)
api_1       |   at bio.overture.ego.service.ApplicationService.getByClientId(ApplicationService.java:238)
api_1       |   at bio.overture.ego.security.CorsFilter.doFilter(CorsFilter.java:53)
api_1       |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
api_1       |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
api_1       |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
api_1       |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
api_1       |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
api_1       |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
api_1       |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
api_1       |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
api_1       |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
api_1       |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
api_1       |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
api_1       |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
api_1       |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
api_1       |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api_1       |   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
api_1       |   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
api_1       |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api_1       |   at java.base/java.lang.Thread.run(Unknown Source)
```

Upon clicking on the button `Google`, the following exception is thrown. I'm redirected to the page `http://localhost:8081/oauth/login/google?client_id=ego-ui`, with a 404 error.

```console
api_1       | 2022-05-27 01:55:10,822 [http-nio-8081-exec-3] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
api_1       | bio.overture.ego.model.exceptions.NotFoundException: The 'Application' entity with clientId 'ego-ui' was not found
api_1       |   at bio.overture.ego.model.exceptions.NotFoundException.checkNotFound(NotFoundException.java:35)
api_1       |   at bio.overture.ego.service.ApplicationService.getByClientId(ApplicationService.java:238)
api_1       |   at bio.overture.ego.security.CorsFilter.doFilter(CorsFilter.java:53)
api_1       |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
api_1       |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
api_1       |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
api_1       |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
api_1       |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
api_1       |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
api_1       |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
api_1       |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
api_1       |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
api_1       |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
api_1       |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
api_1       |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
api_1       |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
api_1       |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api_1       |   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
api_1       |   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
api_1       |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api_1       |   at java.base/java.lang.Thread.run(Unknown Source)
```

![image](https://user-images.githubusercontent.com/3056480/170613224-37457496-a2ad-48bb-b8c8-8588ff360000.png)

**Comment by blabadi** [comment]
Yeah I forgot to add a step to seed some DB data, I opened a PR here: https://github.com/overture-stack/ego/pull/651/files

**Comment by blabadi** [comment]
@tschaffter  The PR was merged a while back, I hope everything worked out well for you ? if not feel free to ask any other questions or let me know to close this ticket

**Comment by tschaffter** [comment]
@blabadi I can now successfully launch Ego and access its dashboard. Thanks!

**Comment by blabadi** [comment]
Glad to hear that !

I also thought to point out that we have something that can help in speeding up the process of exploring the full line of overture services, without having to deploy and troubleshoot each component as standalone docker container.

if that's your goal check our DMS which is a lightweight package to run and explore overture components on a single machine with minimal configurations and technical know how: https://www.overture.bio/documentation/dms/
